#!/usr/bin/env bash
# script

apt-get update
apt-get install haproxy -y

echo "
	frontend cfg_front
        	bind *:80
        	mode http
        	option httpclose
        	default_backend cfg_back
	backend cfg_back
        	balance roundrobin
        	server 372555-web-01 54.227.197.221:80 check
        	server 372555-web-02 54.157.162.112:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
