#!/usr/bin/env bash
# script

apt-get update
apt-get install haproxy

echo -e "\nfrontend cfg_front\n\tbind *:80\n\tmode http\n\toption httpclose\n
\tdefault_backend cfg_back\nbackend cfg_back\n\tbalance roundrobin\n\tserver 372555-web-01 54.227.197.221:80 check\n\tserver 372555-web-02 54.157.162.112:80 check\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
