#!/usr/bin/env bash
# configures nginx server to start with nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
# run the command service nginx start
sudo -u nginx service nginx start
